# Generated by Django 4.2.5 on 2023-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='media/')),
                ('image_file', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
