# Generated by Django 4.2.5 on 2023-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='image_file',
            field=models.ImageField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='video_file',
            field=models.FileField(upload_to='file/'),
        ),
    ]
