# Generated by Django 4.2.5 on 2023-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_detection', '0002_alter_fileupload_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='video_file',
            field=models.FileField(upload_to=''),
        ),
    ]
